# References {.unnumbered}

::: {#refs}
@article{knuth84, author = {Knuth, Donald E.}, title = {Literate Programming}, year = {1984}, issue_date = {May 1984}, publisher = {Oxford University Press, Inc.}, address = {USA}, volume = {27}, number = {2}, issn = {0010-4620}, url = {https://doi.org/10.1093/comjnl/27.2.97}, doi = {10.1093/comjnl/27.2.97}, journal = {Comput. J.}, month = may, pages = {97--111}, numpages = {15} }
:::

Ok, A.O., Akar, O., Gungor, O., 2012. Evaluation of random forest method for agricultural crop classification. European Journal of Remote Sensing 45, 421--432. https://doi.org/10.5721/EuJRS20124535

Vavlas, N.-C., Waine, T.W., Meersmans, J., Burgess, P.J., Fontanelli, G., Richter, G.M., 2020. Deriving Wheat Crop Productivity Indicators Using Sentinel-1 Time Series. Remote Sensing 12, 2385. https://doi.org/10.3390/rs12152385

WANG Shuang, DING Jian-li, WANG lu, NIU Zeng-yi. Remote sensing monitoring of soil salinization based on surface spectral modeling\[J\]. , 2016, 39(1): 190-198.

Ram C. Kafle, Keshav P. Pokhrel, Netra Khanal & Chris P. Tsokos (2019) Differential equation model of carbon dioxide emissions using functional linear regression, Journal of Applied Statistics, 46:7, 1246-1259, DOI: 10.1080/02664763.2018.1542667

J.O. Ramsay and B.W. Silverman, Functional Data Analysis, 2nd ed. Springer, New York, 2005.

Tsokos C P, Xu Y. Modeling carbon dioxide emissions with a system of differential equations\[J\]. Nonlinear Analysis: Theory, Methods & Applications, 2009, 71(12): e1182-e1197.
